name: Repro

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        i: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
      fail-fast: true
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Dump sysconfig
        run: python3 -m sysconfig
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y qemu-kvm zstd ${{ 'libomp-$(clang --version | sed -rn "s/.*clang version ([0-9]+).*/\\1/p")-dev' }}
      # Upstream defaults to world-read-writeable /dev/kvm. Debian/Ubuntu
      # override this; see
      # https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892945. We want the
      # upstream default.
      - name: Set up KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /lib/udev/rules.d/99-fix-kvm.rules > /dev/null
          sudo udevadm control --reload-rules
          sudo udevadm trigger -w /dev/kvm
      - name: Build
        run: python setup.py build_ext -i
      - name: Test
        run: python3 -m vmtest.vm -k 6.16.8-vmtest36.1default bash -c "for ((i = 0; i < 200; i++)); do echo \$i; $(which python3) -B ./repro.py || exit 1; done"
